from .auth.routes import mod as mod_auth
from .services.routes import mod as mod_services 
from .projects.routes import mod as mod_projects 
from .pages.routes import mod as mod_pages   
from .dashboard.routes import mod as mod_dashboard
from .user_crud.routes import mod as mod_user_crud
from .productos_crud.routes import mod as mod_productos_crud
from .shop.routes import mod as mod_shop
from .compras.routes import mod as mod_compras
from .terminos.routes import mod as terminos_condiciones